name: Double Lucky
favicon: null
layout_spectrum: 1
typography_spectrum: 0.458893948700279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.39006643323227763
  lightness: 0.702091404935345
  saturation: 0.3518631374463439
  rhythmicContrast: 1
purpose: []
